# Configuration for the AIS Data Analysis Pipeline
# This file contains key parameters that control the behavior of the processing scripts.

# --- S3 AIS Processor Configuration ---
# S3 bucket and path settings
s3:
  bucket_name: "ais-pipeline-data-10179bbf-us-east-1"
  input_prefix: "raw/"
  output_prefix: "cleaned/"

# Data processing parameters
processing:
  # The maximum plausible speed for a vessel in knots. Any position reports
  # that imply a speed greater than this will be filtered out.
  speed_thresh: 80.0
  
  # The minimum time gap between two position reports to be considered a new,
  # distinct voyage (track_id).
  gap_hours: 6.0
  
  # Number of rows to process in each chunk (memory management)
  chunk_size: 500000
  
  # Enable track interpolation to regular time intervals
  interpolate: false
  
  # Interpolation interval in minutes (if interpolation is enabled)
  interpolate_interval: 10

# Performance settings
performance:
  # Number of parallel processes to use (set to 1 for single-threaded)
  num_processes: 1
  
  # Maximum number of files to process in one batch
  max_files_per_batch: 10

# --- Legacy settings (for backward compatibility) ---
# These are kept for compatibility with existing scripts that expect flat config
speed_thresh: 80.0
gap_hours: 6.0